### ISSUE TITLE
commit hash detection failure when added as submodule

### ISSUE THREAD

**Issue by mjheagle8** [luakit/luakit#148] opened 2012-10-28 16:50 UTC
when i created a git submodule with this repo, i get the following error repeated when compiling:
`ERROR: Commit hash detection failure. Dear packager, please figure out what has gone wrong and or get in touch with us`
i found that this error was coming from build-tools/getversion.sh.  however, i discovered that `git describe --tags --always` was able to execute successfully.  the problem was that the condition preceding this command was returning false.  the attached small patch yielded a compile without this error for me.

http://sprunge.us/Segi

thanks!
- mjheagle

**Comment by aidanholm** [comment] 2017-07-31 23:54
I cannot reproduce this, and it's been a long time since it was reported, so I'm closing this to keep the issue tracker focused; please reopen if you're still experiencing this and want to solve it.

**Closed by aidanholm** 2017-07-31 23:54 UTC
Labels: outdated
