### ISSUE TITLE
Luakit not being able to open hinted links

### ISSUE THREAD

**Issue by B83C** [luakit/luakit#916] opened 2021-03-27 04:20 UTC
**Current Behavior:**
I am not able to open some of the hinted links generated by pressing 'f' key.
It doesn't happen all the time, but it is somewhat annoying considering that for every bugged pages, I would have to reload/restart luakit, or use ';o' to temporarily fix the issue.  

Below is a video clip of the issue.
https://user-images.githubusercontent.com/72597973/112709696-876b7e80-8ef6-11eb-939d-b2aebb44bd69.mp4
I was constantly pressing 'r', but nothing seems to be executing whatsoever.

**Desired Behavior:**
Have luakit open up links to be followed.

**How can we reproduce it (step by step):**
I have no idea, is it only me who has been affected?

**Environment:**

Linux Distribution & Version:
Output of `luakit --version`:
luakit 2.0.0
  built with webkit 2.30.1 (installed version: 2.30.6)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment] 2021-03-29 06:43
There have been a couple of releases since 2.0.
Can you try the version in git?

Edit: Actually, i think i can reproduce it.
I see the issue happening (or not) depending on how far the page has scrolled.
Are you able to confirm that?

**Comment by B83C** [comment] 2021-03-29 13:50
I have tried compiling luakit on the develop branch and the problem seems to persist across all the previous releases, meaning I still can't open some links sometimes. However, I have noticed that scrolling back and forth kind of works but not always, and there's a slight issue where hinted links direct u to the wrong URL (it's like having multiple URLs shifted in the mapping, whilst entering the unupdated hint label on screen).

**Comment by taobert** [comment] 2021-03-29 22:07
Firstly (or what _should_ have been firstly): thanks for the bug report.
I'm having a play with it. Thanks for confirming that scrolling (sometimes) helps.

WRT being directed to the wrong URL,
when luakit puts up the follow hints, the default behaviour is to allow matching of either the follow hint _or_ the link text.
If you don't already have them, could you test this again with these lines in your `userconf.lua`:
```
local follow = require "follow"
-- Match only hint label text
follow.pattern_maker = follow.pattern_styles.match_label
```
This may show whether the misdirections you're seeing are caused by the follow hints occurring in link text.
If this _is_ the cause of the misdirections, then this is arguably also a bug,
but i don't find matching against the link text particularly useful,
and turning it off is not particularly hard (if a little esoteric).
In principle, the follow hints could be sieved so that no patterns present in link text were presented to the user,
but there's not much that can be done about multiple links containing the same string, 
so i don't think this would really cure anything, just push it from an edge case to a corner case.

**Comment by B83C** [comment] 2021-03-30 07:04
Well, after digging around for hours, I think I might have found the culprit to the issue.

If you look clearly into this piece of code located in /usr/local/share/luakit/lib/follow_wm.lua, or if you have pulled the repository, /lib, you will notice that it invokes a click action on the element which is redefined witih "document.elementFromPoint(..) or element". One can tell that doing so is very erroneous and can result in a very inaccurate behavior ( having the wrong elements being clicked ). And one more strange behavior when I was debugging the elements was that the values in element.rect (r.left, r.width, ...) were never updated, which also resulted in the wrong element overriding the current one. 

Location : lib/follow_wm.lua:10
```
local evaluators = {
    click = function(element, page)
        local tag = element.tag_name
        if tag == "INPUT" or tag == "TEXTAREA" then
            local t = element.attr.type
            if t == "radio" or t == "checkbox" or t == "submit" or t == "reset" or t == "button" then
                element:click()
                return
            else
                element:focus()
                return "form-active"
            end
        end
        -- Handle <a target=_blank> indirectly; WebKit prevents opening a new
        -- window if not initiated by the user directly
        if tag == "A" and element.attr.target == "_blank" then
            ui:emit_signal("click_a_target_blank", page.id, element.href)
            return
        end
        -- Find the element directly in the centre of the link
        if element.child_count > 0 then
            local r = element.rect
            local doc = element.owner_document
            element = doc:element_from_point(r.left + r.width/2, r.top + r.height/2) or element
        end
        element:click()
    end
```

**Solution:**
Comment out the lines below
```
        if element.child_count > 0 then
            local r = element.rect
            local doc = element.owner_document
            element = doc:element_from_point(r.left + r.width/2, r.top + r.height/2) or element
        end
```
This is what it should like:
```
        --if element.child_count > 0 then
        --    local r = element.rect
        --    local doc = element.owner_document
        --    element = doc:element_from_point(r.left + r.width/2, r.top + r.height/2) or element
        --end
```
While this has fixed the issue, some other problems can also arise from this patch too. and before yelling me for not doing it correctly, I want to say that I have no experience with lua whatsoever, and I could be wrong, but I am happy to accept any reprehensions.

**Comment by taobert** [comment] 2021-03-30 08:41
Yes. I got to the same place independently.:)
I'm disinclined to just remove those lines,
both because i don't know why they're there, and because i still don't understand why there's a problem.
The issue more specifically is that `doc:element_from_point` returns a different element depending on the scroll position of the page,
(and for me at least returns an element far outside the element we're after) but i haven't figured out why yet.
The `element.rect` is the same in each case.
`element.rect` is "The position of the element within the containing DOM document",
so perhaps `doc:element_from_point` is using an inappropriate origin.

**Comment by B83C** [comment] 2021-03-30 09:12
So I guess it's more of a problem from the internal implementation of DOM elements in luakit than the modules themselves, right?

**Comment by taobert** [comment] 2021-03-30 09:54
My guess is that there's a disjunction with where the co-ordinates' origins are.
When i've been testing, (using github's PR page) if i scroll to the top,
and put my mouse over the Issues link, then scroll to the bottom,
and use follow to (attempt to) click the Issues link,
the element returned by `element_from_point` is close to the mouse.
This would happen if the element's `rect` is relative to the top of the DOM document, 
but `element_from_point` returns one relative to the window.
Not conclusive, but where i'm thinking ATM.

`doc:element_from_point` calls `webkit_dom_document_element_from_point` which 
"has been deprecated since version 2.22 and should not be used in newly-written code.
Use JavaScriptCore API instead" but i don't know how pertinent that is.

**Comment by taobert** [comment] 2021-03-31 08:51
Try this for me.
I haven't used it much, but it seems to correct the issue in the limited testing i've done.
If it satisfies you, then it'll also want the `scrollX` added before it gets PRed.
If you'd prefer not to patch by hand, i can put it in a branch you can checkout.

```
diff --git a/lib/follow_wm.lua b/lib/follow_wm.lua
index 4808be72..15afc809 100644
--- a/lib/follow_wm.lua
+++ b/lib/follow_wm.lua
@@ -30,7 +30,8 @@ local evaluators = {
         if element.child_count > 0 then
             local r = element.rect
             local doc = element.owner_document
-            element = doc:element_from_point(r.left + r.width/2, r.top + r.height/2) or element
+            local scrollY = page:eval_js([=[ (function () { return  window.scrollY; })() ]=])
+            element = doc:element_from_point(r.left + r.width/2, r.top - scrollY + r.height/2) or element
         end
         element:click()
     end,
```

**Comment by c0dev0id** [comment] 2021-04-02 13:12
I think moving to the JavaScriptCore API would be a good task to take on. I just don't know (yet) how to start.

**Comment by taobert** [comment] 2021-04-03 05:39
> I think moving to the JavaScriptCore API would be a good task to take on.

Well thats not untrue.
Presumably, eventually the deprecation will actually be effected (as opposed to documented), and Luakit will be forced to update. Getting a jump on that is probably prudent as there are lots of functions giving that deprecation notice.




However, i don't think the deprecation notice is relevant to _this_ issue.
The equivalent js command is `document.elementFromPoint()`, which takes co-ordinates relative to the current viewport, so subtracting the `scrollX` and `scrollY` from Luakit's `element.rect` will still be necessary.
As a side note, the js analog of `element.rect` is `window.document.documentElement.getBoundingClientRect()` which returns coordinates relative to the viewport, so `element.rect` seems to be quite unfashionable in using the document as it's origin. It also seems to only be used in a couple of places. (Other than here, `lib/image_css_wm.lua` uses it to test whether an img is taller than the body, and if so, to assign a `verticalOverflow` class.) It seems to be created in `luaH_dom_element_client_rects` using the `webkit_dom_client_rect_get...` suite of functions, which seem poorly documented. (There are no links for them in [the webkitgtk reference docs](https://webkitgtk.org/reference/webkitdomgtk/stable/index-all.html).)


Furthermore, i'm not actually sure why this clause (`if element.child_count > 0 then...`) is necessary, and @B83C's solution of just removing it might be preferred. My take on the current code is that it clicks the central child because that's the closest modelling of what would happen if a user actually mouse-clicked it, and that click event then bubbles up through the stack until something reacts to it. But it seems to me that the element had the hint attached to it because of it's clickability. If a child element also has clickability, it probably has it's own hint, and if the user wanted that clicked, they would have used that hint.
It's @aidanholm's code, and he might be able to clarify why i'm wrong.

Whichever approach is preferred (subtracting the `scrollX` and `scrollY` or deleting the clause), i'm happy to do a pull request (unless @B83C would like the PR cred).

**Comment by c0dev0id** [comment] 2021-04-04 12:27
Wow, good analysis @taobert. May I ask how you debug lua? I'm usually throwing in "inspect.lua" and then print stuff vie luakits :lua evaluation. But that's not getting me very far in analyzing stuff here, because I can't be in hint mode and then type :lua inspect...

My other approach is to add a million print/msg statements to get a clue.

**Comment by taobert** [comment] 2021-04-05 04:06
Clumsily.
`:lua` if i can, (but adding print statements to the code is often faster in the long run,
as i'll usually want the same information printed under different situations,)
along with lots of grepping and supposition. (I haven't really found a good ctags for lua yet.)
Specifically in this issue, printing the element's innerHTML before and after reassignment showed me that the new element was clearly not the one that was wanted. As the new element was being determined by webkit based on a supplied position, then either there was some mystical webkit dysfunction (a possibility), or the position was wrong.

I hadn't known about inspect.lua, i'll look into it.
For tables i've been using [Penlight](https://github.com/lunarmodules/Penlight)'s `pretty` (`require("pl.pretty").dump(...)`) which serves it's purpose, but is a little clunky to type.
When i was playing with this issue, i explored [debugger.lua](https://github.com/slembcke/debugger.lua.git), and it helps a bit,
but it's also a bit clunky to use (breakpoints need to be explicitly inserted in the code).
You can get a stacktrace with `print(debug.traceback())` which can be faster than adding prints to each function you suspect is going to be called, and i'm using [StackTracePlus](https://github.com/ignacio/StackTracePlus) (see #626 for usage), to provide a bit more information.

Apart from that, i have the webkit git repo cloned for reference when i feel the need to look below the surface to try to shed light on why things don't seem to work as i imagine they ought to, but i dont really have the stomach for that if i can avoid it.

**Closed as completed** 2021-06-07 18:29 UTC
