### ISSUE TITLE
One window per tab mode

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#590] opened 2017-11-12 11:54 UTC
Can you add some setting to make only one window per tab(many browsers have it)? The case is that with exwm tabs can be easily integrated into emacs as regular buffers.

**Comment by ghost** [comment] 2017-11-12 15:03
I have replaced the unique intance handling in `rc.lua` with this:

At the top of the script:
```
local unique_instance = require "unique_instance"
unique_instance.open_links_in_new_window = true
```

At the bottom (after "end user script loading") add this and delete everything else:
```
window.new(uris)
```

This ensures that whenever you call `luakit <url>` a new window gets created and existing luakit instances are not reused.

Check and compare with [my full rc.lua](https://gist.github.com/xkpd3/561ae06deffb1124669956412de67dd7)

Does this help?

Keep in mind that my solution disables the session handling.

EDIT: may be one of both changes is redundant. I think replacing the unique handling at the bottom at the script was my first solution and later on the `unique_instance.open_links_in_new_window` got introduced.

**Comment by schvabodka-man** [comment] 2017-11-12 15:18
Ok, thx, but would be great if there somewhere would be documentation with all that stuff, because looking at source code for "help" isn't that great

**Comment by aidanholm** [comment] 2017-11-13 22:57
This seems similar to #509; is that what you want @schvabodka-man?

**Comment by c0dev0id** [comment] 2018-10-21 20:39
The issue is 11 months old and a solution has been implemented in the referenced issue. I'm closing this now.

**Closed as completed by c0dev0id** 2018-10-21 20:39 UTC
