### ISSUE TITLE
Frequent Webkit Crashes on FreeBSD

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#688] opened 2018-03-11 12:34 UTC
Hello,

Since I started using Luakit mid of last year, I experience frequent webview crashes. It happens mostly on complex websites. I can usually reproduce it by clicking through products on amazon within a couple of minutes.

Since then, luakit has changed a lot, webkit has changed as well, but this crash still happens. I'm currently using luakit git-head and webkit 2.19.6.

I suspekt luakit of being the source of the trouble because I am not able to reproduce the issue with other webkit2-based browsers (like vimbrowser).

I've set a breakpoint at "ebview_crashed_cb" and here you can find the stack trace from right after the the crash happened.

```
ASSERTION FAILED: !childItemWithTarget(child->target())
Source/WebCore/history/HistoryItem.cpp(318) : void WebCore::HistoryItem::addChildItem(Ref<WebCore::HistoryItem> &&)
Thread 1 hit Breakpoint 1, webview_crashed_cb (UNUSED_view=0x81d4be900, w=0x1a7fb88) at widgets/webview.c:1246
1246        webview_data_t *d = w->data;
```

I tried to deactivate any "history" functionality within luakit, but it did not have an effect. I also tried the standard configuration -> no difference.

Full backtrace:
https://gist.github.com/xkpd3/b356c300e977d3d6283f2b03149ad366

**Comment by aidanholm** [comment] 2018-03-11 13:44
The `webview_crashed_cb` callback is called in the main UI process, but the crashes occur when a web process segfaults; so the backtrace at that point isn't going to show anything relevant to the crash. To obtain a better backtrace, you'd have to attach to the web process with a debugger when luakit starts, and then wait for the web process to crash; the web process will then be paused with the state of the crash, and you can take a backtrace / inspect variables. You might also want to limit the number of web proceses to 1, so you only have to attach to one web process.

**Comment by ghost** [comment] 2018-03-11 20:51
I started luakit with one process, attached gdb to it and set a breakpoint at WTFCrash.
This is the trace I got when the breakpoint was hit:
https://gist.github.com/46e430ed2905fb5f063b77a49335e6e6

**Comment by aidanholm** [comment] 2018-03-12 06:18
Ok, that looks like a luakit bug, but the backtrace doesn't say much because the `luakit.so` file has been stripped; could you build a version with symbols and then reproduce?

**Comment by ghost** [comment] 2018-03-13 14:08
I had the WebProcess limited to 1 already. I attached to it with gdb and let it crash. The backtrace at the segfault is way to big to copy and paste. What I see looks very gibberish to me.

Here is the core file: [removed] (398MB)

**Comment by ghost** [comment] 2018-03-13 14:17
Hmm you're probably not able to read the core file format. Nevermind, I try to get something out of it.

**Comment by ghost** [comment] 2018-03-13 18:15
This is a full backtrace for the WebProcess:
https://gist.github.com/ef07543a3787d24df5bbc830d2392574

**Comment by aidanholm** [comment] 2018-03-14 15:00
Thanks! This isn't terribly illuminating, unfortunately. The only thing that jumps out is the value of L (`L = 0x1378`), which seems very low for a pointer. It could conceivably be corrupted somehow, which then causes a segfault when the Lua VM is accessed. This fits both backtraces, which both crash inside Lua, but from completely different parts of luakit.

To test this hypothesis, you could start luakit, attach gdb to the web process, and add a write watchpoint to `common.L`. Then just continue browsing; if a write triggers the watchpoint, you'll be able to see the backtrace that causes the corruption.

**Comment by ghost** [comment] 2018-03-14 19:42
Hmm, it segfaulted again without stopping at the `common.L` watchpoint. My assumption was that it should stop there before segfaulting.

Backtrace: https://gist.github.com/40eacacca529876a604883f676dfe0a6

But L = 0x1378 is in there again.

**Comment by aidanholm** [comment] 2018-03-15 13:42
Does `common.L` have that value initially? That may simply be where it is mapped (if you don't have ASLR). To debug this further you might need to install luajit symbols. Alternatively, a possible workaround is to build with regular lua, since all of the segfaults have been inside luajit

**Comment by c0dev0id** [comment] 2018-10-16 20:57
The ghost above is me :) Please close this issue for now. I might recreate and reference it with my current user when I have the time (and passion) to dig into it again.

**Closed as completed** 2018-10-17 07:28 UTC
