### ISSUE TITLE
`del_word` in `readline.lua` not UTF8-aware

### ISSUE THREAD

**Issue by hofheinz** [luakit/luakit#525] opened 2017-09-22 19:19 UTC
The `del_word` function in `readline.lua` does not work as expected when the current contents of the line contain UTF8/wide characters. The reason is that `del_word` treats the position of the editing caret (which counts actually visible characters) directly as a character index to `string.sub` (which counts wide characters as several bytes/characters). To reproduce, use a UTF8 locale and enter ":äbc äbc äbc äbc", press `^W` a few times.

Looking at `del_word`, I would suppose that fixing this requires `string.wlen` (luakit's UTF8-aware `string.len` function), something like lua 5.3's `utf8.offset`, and/or UTF8-compatible `string.find` functions.

I can offer a PR that implements a `string.woffset` function (like `utf8.offset` in lua 5.3) using glib, and a modified `del_word` function (that currently considers all wide characters as non-word characters -- not sure how to best fix that). Please let me know if this could be helpful, or if there is a better way to do this.

**Comment by aidanholm** [comment] 2017-09-24 12:05
I found one UTF-8 implementation of the string functions: https://github.com/starwing/luautf8. Code quality looks decent; we could consider adding this as a dependency if it proves useful.

I think the problem with `del_word` not considering wide characters is caused by the use of the `%w` group in patterns; this should probably be `%S` instead.

**Comment by hofheinz** [comment] 2017-09-24 16:47
Regarding `%w` vs. `%S` in `del_word`: yes, that seems to work. (I tried to check if the repository you mentioned somehow allows to redefine/extend `%w` to wide characters, but it seems this is not so.)

Regarding the `luautf8` repository: yes, that might come in handy in other places as well. Lua 5.3 has its own `utf8` functions, but the `luautf8` package appears to have extended functionality (e.g., support for `gsub`). I have no experience adding a dependency, but would be happy to modify the `del_word` parts of this.

For completeness, I'm still making a PR (that rolls its own `string.woffset` function from the corresponding glib function, and modifies `del_word` accordingly). Maybe parts of this are useful.

**Comment by aidanholm** [comment] 2017-09-25 02:49
`%w` matches any alphanumeric character, so that was a bug in the initial implementation of `del_word`.

I had a quick look at your PR, and the implementation looks good, but I'd prefer using a dependency that provides a full set of compatibility functions, instead of adding new functions as they become necessary, for these reasons:
 - it shifts the burden of maintenance
 - it makes it less likely that luakit will end up with a whole bunch of poorly organized functions that we're stuck maintaining
 - `luautf8` provides compatibility with Lua 5.3

Adding a dependency is a packaging task. Just make sure you have it installed (e.g. `lua51-utf8` on the AUR), and add `local utf8 = require 'lua-utf8'` in the diff for testing. Before merging it'll be necessary to load the module by default from C.

**Comment by hofheinz** [comment] 2017-09-25 08:55
Thanks for the explanation! Ok, I'll use that package then and will update the commit later today. (Note: on OpenBSD, that package exists, but on Debian, the UTF8 package doesn't appear to exist. Is there any specific way to deal with this? I'm just mentioning this to avoid breaking Debian packaging somehow.)

**Comment by aidanholm** [comment] 2017-09-25 09:38
@groolot would know more than I about packaging for Debian, but if it's not already there as a package I guess the easiest solution is probably to embed it for the Debian package. Not really sure.

**Comment by groolot** [comment] 2017-09-25 09:55
Indeed, it seems to not be in the Debian archive.

If the embeded code was tested on Lua5.3 and our package depends on Lua5.1 make sure that `luautf8` do not break compatibility.

And then, while the needs are not provided as Debian packages, we have to embed them.

But we have to be aware of:
 - the package have to be incorporated as is
 - any change to the code should be done externaly when possible (this way, transition to Debian packaging will be easy)

**Comment by groolot** [comment] 2017-09-25 10:00
@hofheinz may want to package http://github.com/starwing/luautf8 for Debian as `lua-utf8` and then we just depend on it :smile:

**Comment by aidanholm** [comment] 2017-09-25 10:02
The dependency to be added is specifically designed to backport features to Lua 5.1, so there shouldn't be any such problems with 5.1 vs 5.3. It'd be nice if it were packaged for Debian, but it may be easier to just embed it for now. We won't need to make any changes to the new dependency, and we only need to add a single `.so` file from the dependency to our `lib/` directory (might need license note as well?).

**Comment by hofheinz** [comment] 2017-09-25 10:25
@groolot To be honest, I'd prefer not to (also, I haven't done any packaging before).

@aidanholm Not sure if this dependency will vanish for Lua 5.3: http://github.com/starwing/luautf8 provides much more than Lua 5.3's utf8 library. For instance, http://github.com/starwing/luautf8 provides a UTF8-aware `gsub` implementation. (Of course, we can also implement this on top of Lua 5.3 without external libraries, should not be very hard.) For many problems (including the one from this issue), Lua 5.3's `utf8` support should be more than enough, though.

**Comment by aidanholm** [comment] 2017-09-25 10:40
Not sure what you mean by "vanish for Lua 5.3".

But now that I take a closer look, the GitHub page does say that it supports LuaJIT, but doesn't mention Lua 5.1... the AUR page mentions Lua 5.1 explicitly, however, so it should be fine; just need to test it.

**Comment by aidanholm** [comment] 2017-09-25 11:33
Hm, one problem with luautf8, at least on Arch, is that it requires luarocks as a build-time dependency, which isn't great. I don't particularly want to add more makedepends. Unfortunately, there aren't many great options here: there aren't many other comparable implementations.

**Comment by hofheinz** [comment] 2017-09-25 11:34
@aidanholm: With "Not sure if this dependency will vanish for Lua 5.3" I meant that if we use http://github.com/starwing/luautf8 now, then upgrading to Lua 5.3 does not make this dependency obsolete. (Lua 5.3 has some UTF8 support, but not to the extent that this external library provides.)

I wrote that because I had the impression that your comment that "The dependency to be added is specifically designed to backport features to Lua 5.1, so there shouldn't be any such problems with 5.1 vs 5.3" assumed that this library would not be necessary anymore with 5.3. (If you did not want to say that, I simply misunderstood.)

**Comment by hofheinz** [comment] 2017-09-25 11:38
One option could be: implement some minimal version of `utf8.*` now (basically with only `utf8.len` and `utf8.offset`, this covers many cases already and can be/is done cheaply, with glib calls), and drop those when moving to Lua 5.3 at some later point. (The luautf8 library does provide much more, but I'm not sure we really need all that.)

(The difference to the current PR/the current situation with `string.wlen` is simply a slightly different interface that is compatible with Lua 5.3: `string.wlen` -> `utf8.len` and `string.woffset` -> `utf8.offset`.)

**Comment by aidanholm** [comment] 2017-09-25 11:56
Moving to 5.3 implies dropping LuaJIT support, which isn't ideal; luakit will stay on 5.1 for the forseeable future. The main advantage of having compatibility with 5.3 is that it's possible to use _other_ code that expects a (partial) 5.3 environment without modification.

I think your suggestion is probably the best option. It resolves all the packaging issues, and won't force us to break compatibility if we reconsider in the future. Since you already have done most of the work, the only remaining bit is to move it into a `utf8` clib. This should be in `common/clib/`, as it's conceivable that web processes will want to take advantage of utf8 handling. Let me know if you need help with this!

I guess `string.wlen` should be deprecated and moved to that library as well?

**Comment by hofheinz** [comment] 2017-09-25 12:47
Ok, I'll try that. (`string.wlen`: I'll check for other uses of that function, and it's probably a good idea to have it around for a bit, in order not to break existing code, but yes, in principle I guess that should be deprecated.)

**Closed as completed** 2017-10-01 15:24 UTC
Labels: bug
