### ISSUE TITLE
Hint following engine gets confused

### ISSUE THREAD

**Issue by isovector** [luakit/luakit#786] opened 2019-05-07 14:16 UTC
## I'm submitting a ...
Bug Report

## Current Behavior
Sometimes I'm unable to follow hints; it looks like the hint DFA gets confused.

For example, let's say [I'm on this page](https://hackage.haskell.org/package/gi-webkit2webextension) and I want to go to *edit package information* (hint: `tr`):

![2019-05-07-111019_934x261_scrot](https://user-images.githubusercontent.com/307223/57306169-bd13de00-70b8-11e9-8267-f2b5f5e8225e.png)

So I type `tr`, expecting to go there:

![2019-05-07-111027_892x230_scrot](https://user-images.githubusercontent.com/307223/57306795-d5382d00-70b9-11e9-9740-77dd4ffb469c.png)

But luakit gets drunk! It also keeps ahold of `vr` and `rt` too! Hitting `<CR>` doesn't go to the hint I want.

## Expected Behavior
Typing hints should just work!

## Reproduction Instructions
Relevant bit of `luakit.rc`:

```lua
local select = require "select"

select.label_maker = function ()
    local chars = charset("qwertasdfghcvb")
    return trim(sort(reverse(chars)))
end
```

## Environment
```
$ luakit --version
luakit 2.1-12-g65f3f8d2
  built with webkit 2.24.0 (installed version: 2.24.0)

$ uname -a
Linux monoid 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux
```

**Comment by isovector** [comment] 2019-05-07 14:19
I noticed when rying to take the screenshots for this that the hints are nondeterministic; upon reloading the page my hint for *edit package information* is now `sw`. Maybe this is related somehow?

**Comment by isovector** [comment] 2019-05-07 14:24
The original `label_maker` works just fine on this page.

**Comment by aidanholm** [comment] 2019-05-09 15:20
Thanks for the report! Actually, this is not a bug, although you're not the first to open an issue for this somewhat confusing default: what's happening is that by default the follow mode matches against the link text as well as the hint: bytes**tr**ing and **tr**ansformers. This also occurs with numerical hints, although less frequently of course.

You can change this behaviour with:
```lua
-- Match only hint label text
follow.pattern_maker = follow.pattern_styles.match_label
```

**Comment by isovector** [comment] 2019-05-09 15:40
Cool, that makes sense, though it's a super confusing default! Thanks for the fix, should I close this?

**Comment by aidanholm** [comment] 2019-05-11 06:45
I agree, it should probably be changed, as we've had a few people confused by this. No worries, I'll close it :)

**Closed as completed by aidanholm** 2019-05-11 06:45 UTC
Labels: question
