### ISSUE TITLE
luakit ignores custom Compose key settings

### ISSUE THREAD

**Issue by krigstask** [luakit/luakit#89] opened 2012-06-09 06:13 UTC
Despite being GTK+-app, luakit for some reason ignores custom `~/.XCompose` file.

How to reproduce:

```
$ echo 'include "/usr/share/X11/locale/en_US.UTF-8/Compose"' >> ~/.XCompose
$ echo '<Multi_key> <asciitilde> <equal> : "≈"' >> ~/.XCompose
$ setxkbmap -option "compose:ralt"
$ luakit
```

Now enter any textarea and try to press right Alt, then = and ~. Nothing happens, whereas `≈` should have appeared. But stock combination `Multikey, +, -` for `±` works fine.

Gentoo Linux ~amd64, luakit from git:master HEAD (SHA: d67b2882cbc65659ab0e0e8983ab36f6695c48dc).

**Comment by aidanholm** [comment] 2017-06-15 03:50
Cannot reproduce; XCompose works fine for me. Closing, since this is an old bug.

**Closed by aidanholm** 2017-06-15 03:50 UTC
