### ISSUE TITLE
Selection boxes at the wrong places

### ISSUE THREAD

**Issue by nmeum** [luakit/luakit#203] opened 2013-04-27 19:50 UTC
Sometimes the selection boxes are not where you would expect them...for instance this is the case on xkcd.com, but this is not the only site where I experienced this problem. Here is a screenshot:

![27-04-2013_21-50-31](https://f.cloud.github.com/assets/2326560/434820/ddd4feb0-af73-11e2-873b-7a581ade1121.png)

**Comment by aidanholm** [comment] 2017-06-14 05:59
Caused by xkcd `<body>` element having `display: absolute`.

**Comment by c0dev0id** [comment] 2020-09-05 20:12
Either the issue is fixed meanwhile, of xkcd has fixed their page. I don't see a point in having this issue around any longer... so I close it. But as always - feel free to reopen.

**Closed by c0dev0id** 2020-09-05 20:12 UTC
Labels: bug
