### ISSUE TITLE
[ Question ] Webkit and P2P

### ISSUE THREAD

**Issue by 0Karakurt0** [luakit/luakit#963] opened 2021-10-09 13:50 UTC
Quite stupid question, but still, how do I even check if P2P is working?
Thing is, I'm playing stupid litlle game called bonk.io and it runs on P2P connections between players. Any Cromium-based browser works fine, but anything based on Webkit fails to connect.
Not that it's the end of the world, but it's quite annoying and kind of the last reason why I can't switch to luakit - that bad habbit of mine is quite prominent.
So, any guidence where I can read something to formulate more educated question?
Or maybe even some toggle in webkit innerworkings right away?

**Comment by c0dev0id** [comment] 2023-01-08 19:40
This is not a question for luakit. Maybe webkit2gtk people can help. P2P is not a browser feature but is likely implemented in some javascript that does direct websocket connections to peers. There's no reason why this should not work on webkit.

That being said - other JS heavy pages often break too on webkit browsers. It's a cats and mouse game.

The issue is quite old. I'm closing it. Feel free to reopen, if you have a luakit specific question.

**Closed as completed by c0dev0id** 2023-01-08 19:40 UTC
