### ISSUE TITLE
Support High DPI / Retina Resolution

### ISSUE THREAD

**Issue by niedzielski** [luakit/luakit#279] opened 2015-04-16 16:26 UTC
Chromium / Chrome support high resolution Linux displays with the `--force-device-scale-factor` flag. This option does not seem to be available for Luakit causing most sites to appear half sized on a retina monitor.

**Comment by myf** [comment] 2015-05-22 15:24
im exploring the same option. Since luakit uses webkitgtk underneath it is then up to webkitgtk to support hidpi functionalities first. Here's the bug tracker https://aur.archlinux.org/packages/webkitgtk-hidpi/ and it doesn't seemed to be merged yet but will in the future. If you are using arch there's the aur https://aur.archlinux.org/packages/webkitgtk-hidpi/ . That said I think there is still tweaks need to be done on luakit for the scale factor to work, and whoever is interested in exploring different options please comment here as well.

**Comment by myf** [comment] 2015-05-28 16:50
@niedzielski I just foundone solution. Since webkitgtk takes the `zoom` css tag, all you have to do is.

* in `.local/share/luakit` create a folder `styles` and inside the folder a file `custom.css`

* edit the file to include this line
```css
html {zoom: 2.0;}
```
(of course you can change the scaling factor to whatever you want)

* make sure you include the custom css in `globals.lua`  in your `.config/luakit` folder:
```lua
domain_props = {
    ["all"] = {
        user_stylesheet_uri     = "file://" .. luakit.data_dir .. "/styles/custom.css",
    },
}
```

**Comment by niedzielski** [comment] 2015-06-07 21:28
@myf, great notes! Thanks!

**Comment by aidanholm** [comment] 2017-06-09 21:07
As this issue was opened a year ago, and luakit now uses WebKit 2, I'm closing this issue; feel free to reopen it if this problem still occurs with the new version.

**Closed by aidanholm** 2017-06-09 21:07 UTC

**Comment by IWriteThings** [comment] 2017-08-19 22:06
I am reopening this ticket as @aidanholm seems to imply that the upgrade to webkit2 should solve issues with hi-dpi screens. I may be misinterpreting but is there a way to get the screen to have what amounts to a x2 zoom at all times even on load? Some change to be made in config perhaps?

My resolution is 3840x2160 and I have extremely small text in luakit. Do we need to use the format fix provided by @myf or is there an alternative fix due to webkit2?

DE: XFCE
WM: i3
Resolution: 3840x2160

screenshot of issue attached -

![luakit](https://user-images.githubusercontent.com/11728899/29490416-d6f6b75e-84ef-11e7-9546-8bca3c59d308.png)

**Comment by aidanholm** [comment] 2017-08-20 05:25
You should be able to set `globals.default_zoom_level` to 150--200 or so.
The fix @myf mentioned will work but will also break follow mode, so I don't recommend it

**Comment by IWriteThings** [comment] 2017-08-20 13:25
Just fixed it using that exact method. I was exploring around with settings and changed my default zoom to 150.

For others -

* `cd ~/.config/luakit`

* `vi/vim/pico/edit ~/.config/luakit/globals.lua`

(If this file does not exist you can do the following)

```
cd ~/.config/luakit
cp /etc/xdg/luakit/globals.lua .
```

* find 'default_zoom_level` and change it to 150-ish.

* Restart luakit

This is a single file change that is fairly simple.

I formally petition that this be closed again now. Thank you.

**Comment by aidanholm** [comment] 2017-08-20 13:49
Glad it worked; this should probably go in the FAQ as well

And in fact, this issue is alreeady closed :P I'm not sure if anyone but the original opener (and luakit members of course) can reopen issues

**Comment by ghost** [comment] 2017-08-20 17:10
Also, you can copy and adjust `theme.lua` and use a bigger font to make the tabs and the input bar bigger.

**Comment by aidanholm** [comment] 2017-08-20 20:08
You can also set the theme/global variables directly from your `rc.lua`, without creating a copy of the whole file

**Comment by christf** [comment] 2018-03-30 17:11
actually that is not a fix. The whole gui is too small, not just website. Try :inspect and read some stuff. Also when increasing the zoom level all the buttons are off on web sites.
navigating to paste.debian.net reveals the problem, where huge buttons are shown.

**Comment by guyest** [comment] 2018-12-03 18:34
I find it unfortunate that this is the "solution" offered here and in many GUI softwares that break on HiDPI because its really not a solution. I think a good step towards a proper fix for this by adhering to standards set by X11 would be to respect the settings in the `~/.Xresources` file as many other applications do. I don't know lua, but there must be a way to query for the existence of this file and find the value of the `Xft.dpi` parameter. That could then be used to determine the proper zoom level according to the global default set by the user in DPI units (assuming the default of 96). For example, on my system I have set `Xft.dpi=168`, which corresponds to a zoom level of 175%. I expect luakit to know how to make this adjustment.

I get the argument that it is just a single file to be changed (luakit config), but that falls down if every graphical program I have installed takes that shortcut. Luakit should just look in a reasonable set of places, draw a sane conclusion, and allow the user to override in the (unlikely) event that there is no way that a program can determine the scaling required to print words on a screen. This is what Firefox does, for example. With the high-quality of the luakit project on the whole I think something like this can be accomplished without too much pain; I would be happy to help if someone wanted to point me where to start.

**Comment by aidanholm** [comment] 2018-12-04 14:43
That's completely reasonable. I agree that luakit should detect this automatically.

I think the most straight-forward way to retrieve that value is to use `luakit.spawn_sync("xrdb -query -all")` to retrieve the currently active X resources. This can then be filtered in lua by first splitting it into an array of lines with `lousy.util.string.split()`, finding the line that starts with `"^Xft.dpi:\t"`, extracting the remainder with `match()` and converting it to a number with `tonumber()`.

**Comment by zupatisc** [comment] 2021-06-17 13:49
Was this ever implemented? The current workaround in the README is, in my opinion, insufficient because it doesn't actually scale ui elements. The settings page also seems to show that different elements get scaled differently.

**Comment by taobert** [comment] 2021-06-20 04:43
Well, i don't have a high dpi display to test with, so i can offer opinions, but they're based more on supposition rather than experience.
You don't give much detail about which of the suggestions in this issue you've tried, so it's hard to target further suggestions.
To answer your question, (i assume the "this" you're refering to is  @aidanholm's comment from Dec 2018,) `xrdb` doesn't appear in the source, so no, this doesn't seem to have been implemented.
While i don't know the source anywhere near as well as @aidanholm does, and may be very wrong, i'm unconvinced that this is something that luakit should need to do.

Luakit itself doesn't do much in the way of rendering.
It instead requests prebuilt bits and pieces from webkit/gtk.
I think therefore, that (as @myf suggests) it's gtk's responsibility to render things the size they are specified to be.
This issue's been open for 6 years, and i suspect that it should probably be viewed as a composite of issues which may include:
1 gtk not knowing what the dpi is
2 gtk not correctly using the dpi
3 luakit specifying that things should be drawn at inappropriate sizes
4 websites specifying that things should be drawn at inappropriate sizes.

If by "UI elements" you mean things that webkit-gtk draws itself (right-click menu, web inspector, print dialog?), then the first two are likely to be relevant:

### With respect to 1
You probably want to set the dpi in your `.Xresources` file (eg "Xft.dpi: 163").
Without knowing the dpi, gtk will struggle to render things the right size.
Based on the small amount of testing i've done, (using `xrandr --output <output> --scale 1.63x1.63` to mock up a higher dpi,) adding the dpi to .Xresources (and reloading it with `xrdb -merge ~/.Xresources`) and then restarting luakit changes the size of menus plausibly.
As an aside, the web inspector also has a zoom option in it's settings section, and anything that gtk does may be mungable via gtk's theming infrastructure. (See also #868).

### With respect to 2 
(I gather) there have historically been issues with gtk not doing the right thing.
There's not much that luakit devs can do about this, other than note it and suggest workarounds.
You don't mention which version of luakit and webkit-gtk you're using.
It would be useful if you could test the latest versions of luakit and webkit-gtk and let us know if there are specific things not working.
As always, testing with other webkit-gtk browsers and reporting whether they're doing the right thing will help narrow down whether a given issue is specific to luakit or more systemic.



### With respect to 3 
If by "UI elements" you mean luakit's status bar, tab list, &c.
The default font sizes in the `theme.lua` use pixels:
```
theme.font = "12px monospace"
...
theme.hint_font = "10px monospace, courier, sans-serif"
```
If you have very small pixels then these fonts will be drawn very small.
If you change them to use points (eg "8pt") then they should render more sensibly.
The defaults should arguably be in points, but they're not hard for people to change if they need to.

You also mention the settings page.
From the very quick look i've just done i can see that luakit's chrome pages generally use px sparingly, but in some places maybe inappropriately.
There are 1px borders (which i feel is entirely reasonable), but also:
- `settings_chrome.lua` has some border/margin/height/width things related to tool tips
- `adblock_chrome.lua` has `max-width: 100px;` stipulated for `th:nth-last-child(3), td:nth-last-child(3)`
- `downloads_chrome.lua` has many concerning uses of px

I haven't looked at others, and i haven't confirmed that these are _actually_ causing display issues, but they are probably a bad idea.
What specifically are the problems you see with the settings page?

I'll submit a pull request to correct these at some stage.
It would be useful if you could identify other specific errors, so that i can correct those at the same time.




### With respect to 4
If by "UI elements" you mean UI elements on web pages, then all bets are off.
In my (somewhat out-of-date) experience, it's not uncommon for web developers to mix and match points and pixels (and ems, exs &c) to get something that looks ok on their screen.
If a web page has elements specified to be a certain number of pixels, and you have very small pixels, then they'll be drawn very small.
This is not a bug in Luakit. It can be worked around somewhat by setting the zoom, as is mentioned above.

**Comment by zupatisc** [comment] 2021-06-26 11:06
That's quite the extensive writeup, thanks. I'll try and attach a screenshot as I think it's best to simply see it.
My luakit version as per `--version` is: ```luakit 2.3
  built with webkit 2.30.6 (installed version: 2.32.1)``` I'll see if I can try out the git version later but I think something is conflicting in terms of the lua dependencies because of my neovim install.
In any case, I do set `Xft.dpi: 192` in my `~/.Xresources` file so any applications that honor that should work from that. And lastly, because there are a couple different high resolutions: I run 3840x2160 displays.
![screen](https://user-images.githubusercontent.com/61888674/123510995-03ed3500-d67f-11eb-8168-6a6bc2b0ffcb.png)

**Comment by taobert** [comment] 2021-06-29 03:54
Well, i can see that your status and tab bars are very small.
As i indicated above, this can be ameliorated by changing the font size(s) in `theme.lua`.
You may already have a copy in `~/.config/luakit`, if not, there's a system version in `/etc/xdg/luakit/` that you can copy.
From the picture i'm not sure specifically what the issues you're having with the settings page are _per se_ (apart from the status/tab bar, the text appears to be small but legible), however the stylesheet snippet below makes everything larger.

I'm not really sure that i'm calculating correctly here, if you can see an error, i'm open to being shouted down.
My laptop screen's 13.5" wide.
If i set my pixel count to what you have (`xrandr --output LVDS-1 --scale-from 3840x2160`),
the horizontal resolution would be 3840/13.5 = 247.74 dpi.
Setting this dpi makes the right-click menu display at a plausible size.
The web inspector is still too small, and i have to use it's zoom setting i mentioned above.

Further confounding this (and pertaining to both points 3 and 4 in my comment above) is the fact that (according to [this](https://www.sitepoint.com/understanding-and-using-rem-units-in-css/)) "the font size of the html element ... for most browsers has a default value of 16px", and this seems to be true of luakit (presumably due to it being set by webkit). This means that any sizes which are (sensibly) specified as em/ex/rem/&c. may render poorly on displays whose pixels are a different size to the web developer's. Also, webkit's "user agent style sheet" also has sizes for various elements (including tables and inputs). Unless these elements are are explicitly given sizes by another stylesheet, webkit's style will show through. This stylesheet seems to correct (some of) these quirks and make the settings page render larger (in my hands):
```
/* i really want this to be global */
html, body { font-size: 30pt !important; }
table { font-size: 100% }
input:matches([type="radio"], [type="checkbox"]) {
    width: 0.75em;
    height: 0.75em;
}
```
Obviously a 30pt font is ridiculous as the default, however in my hands this is what worked.
So it seems that at least one of the following is true:
- my understanding of the issue (and scaling/dpi/&c. in general) is inadequate (spoiler alert: it is)
- my calculations above are incorrect (also possible)
- gtk still doesn't correctly deal with dpi (this is kinda hinted at by my needing to use the web inspector's zoom setting)
- my mock-up of dpi is incorrect

Please try these tweaks, and see if you can find a workable default font size for your (real hidpi) display and report back.

**Comment by niedzielski** [comment] 2021-06-29 04:36
Apologies for any distraction. I've unfortunately taken a break from luakit but wanted to share my fuzzy recollection and configuration in case it's useful. I believe [the suggestions](https://github.com/luakit/luakit/issues/279#issuecomment-323550380) by @myf were helpful to me at the time and led to the following configuration:

```
# ~/.config/luakit/globals.lua
globals = {
}

search_engines = {
    google      = "https://google.com/search?q=%s"
}
search_engines.default = search_engines.google

domain_props = {
    ["all"] = {
        user_stylesheet_uri     = "file://" .. luakit.data_dir .. "/styles/custom.css"
    }
}
```

```
# ~/.local/share/luakit/styles/custom.css
html {zoom: 2.0;}
```

I can't say for sure whether these worked or if they would still.

 I don't know anything about X but if I were still having trouble with luakit DPI, I would try the following ~/.Xresources configuration I used for FontForge ([notes on how this number was calculated](https://github.com/fontforge/fontforge/issues/2155#issuecomment-284303748)):

```
Gdraw.ScreenWidthInches: 19.6104496
```

**Comment by taobert** [comment] 2021-07-01 11:33
Thanks @niedzielski.

As a follow up to my last comment, it seems that if `font-size`'s are specified as absolutes (`font-size: medium`, &c.) they're not relative to the font on the root node (`html`), rather they're relative to the `webview.default_font_size` setting, so if someone's wanting to use this, they should set that (and probably `webview.default_monospace_font_size` as well). Once these are set, the style snippet in my last comment reduces to:
```
/* i really want this to be global */
html, body { font-size: medium; }
input:matches([type="radio"], [type="checkbox"]) {
    width: 0.75em;
    height: 0.75em;
}
```

However, there are so many sites which insist on sizing fonts in px, that scaling the webview will probably be the least annoying work-around for the foreseeable future.
