### ISSUE TITLE
Windows Subsystem for Linux PKG_CONFIG_PATH Make Errors

### ISSUE THREAD

**Issue by jeffmaner** [luakit/luakit#604] opened 2017-11-20 20:49 UTC
I'm sure this is a rookie mistake; but the Help and Support page told me to ask here.

I was thrilled to see the possibility of running Luakit web browser on Windows 10 using WSL. I've tried on two different machines, now, and both machines complain of the same issue. None of the dependencies are found. For each dependency I'm given the suggestion of adding the correct path to the PKG_CONFIG_PATH environment variable. I have done `sudo apt-get install <package>` for any missing packages, and I have either installed them, or been told that they're already installed. But `sudo make install` still tells me that they're missing.

I've tried using `whereis` to find any useful pkgconfig files. That's been fruitless.

I've cloned the repo to `/mnt/c/Users/Developer`.

I've tried

```
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
```

as well as

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```

Can you tell me what I'm doing wrong?

**Comment by aidanholm** [comment] 2017-11-21 11:32
Hi! No problem, questions are always welcome here :)

I've never used WSL, so I'm not sure where pkgconfig files would live. @xkpd3, any ideas?

**Comment by jeffmaner** [comment] 2017-11-22 13:26
It turns out that all I had to do was `sudo apt-get install luakit` to get luakit up and running in WSL. Who'd have thought?! Now I'm stuck with my original curiosity of how the heck luakit can run in Windows 10 using WSL. As one would suspect, I'm told `(luakit:20159) Gtk-WARNING **: cannot open display:`. But it looks like others have made it work. Hopefully they'll let me know what I'm missing!

**Comment by aidanholm** [comment] 2017-11-22 16:37
So luakit still won't start? You may want to double-check the version with `luakit --version`

**Comment by jeffmaner** [comment] 2017-11-22 16:47
Interesting.

```
$ luakit --version
luakit
```

A little less informative than I expected. Lol.

Oh, wow! I still have the stdout from setup, including:

```
Setting up luakit (2012.09.13-r1-8) ...
```

**Comment by aidanholm** [comment] 2017-11-22 17:43
I'd guess you've inadvertently installed the older version, which is what ships in the WSL version of ubuntu. I can't remember the appropriate command for apt/dpkg, but have you verified that the pkg-config information is included in the packages you've installed? Also, have you updated with `do-release-upgrade`?

**Comment by jeffmaner** [comment] 2017-11-22 19:22
I'm not sure how to verify that the pkg-config information is included in the packages I've installed. It's been too many years since I was linux-fluent.

I have run `do-release-upgrade` to upgrade to xenial.

I've run `apt-get upgrade` and `apt-get check`. The upgrade did a bit of work. The check found no problems. The end result is still the same. Ugh.

**Comment by aidanholm** [comment] 2017-11-23 03:00
`dpkg -L foo` will list files instaled for `foo`; you'll probably want to pipe the output into `grep -F .pc' to filter to pkg-config files.

Possibly a silly question, but have you `apt-get install`-ed `pkg-config`?

**Comment by jeffmaner** [comment] 2017-11-27 15:31
Ooh! That's a neat one. Gods, I do love linux, and hate that I've been consigned to a competing OS for so many years that I've lost so much of my linux know-how. I ran `dpkg -L luakit`. Cool! But when I piped it to `grep -F .pc`, it came up empty.

Not a silly question at all! I appreciate you asking questions that should be obvious to experts, because they're not necessarily obvious to rusty dinosaurs. I have, nevertheless, `apt-get install`ed `pkg-config`. I ran it again to verify, and was told that I am already running the latest version.

Don't spend any more time on this unless you're bored or simply up for the challenge. I appreciate the time you've already spent. While I'd love to run luakit on my Windows machines, it was more a matter of disbelief and curiosity. Although, now I'm wondering... Maybe I'm just missing some middleware. Luakit is installed under WSL. When I try to run it, after all, luakit gives me a gtk warning that it can't open a display. And it looks like it even tries to enumerate the display, but it fails to do that, too. I wonder if I'm missing some sort of gtk emulation on Windows. Maybe I'll pursue that rabbit and see where I end up.

**Comment by aidanholm** [comment] 2017-11-27 15:47
Luakit won't have any `.pc` files, as it doesn't provide anything that can be linked into other software: you need to check the dependencies :) for example, `dpkg -L libsqlite3-dev` (or whatever the sqlite package is called).

Unfortunately I don't have access to a Windows system to try this out on, but perhaps this (https://askubuntu.com/questions/897846/cant-run-gtk-on-wsl-display-error) is your issue? In screenshots I've seen of luakit running on WSL, I remember seeing what looked like the Xming icon.

I'm happy to help; in fact, others have asked about the PKG_CONFIG_PATH thing, so it'd be good to solve this.

**Comment by jeffmaner** [comment] 2017-12-01 16:03
I finally had a moment to install Xming and try running Luakit. It works! This is so cool. Thanks for your help!

I'm not sure where this leaves the issue of the PKG_CONFIG_PATH thing. I feel like this particular issue should be closed, as my over-all goal--running Luakit on Windows--has been achieved. But because leaving it open might help in the struggle to figure out the config problem, I'm not sure I should close it. So I'll leave that decision up to you, @aidanholm!

Thanks again!

**Comment by aidanholm** [comment] 2017-12-01 18:46
Great to hear! I'll close this; it can always be reopened if needed.

Just to be sure, you should double-check that you have the new version: the version number is displayed in the top-left corner of `luakit://help/`. If that page displays a big list of keybindings instead, you have the old version.

**Closed as completed by aidanholm** 2017-12-01 18:46 UTC
Labels: question

**Comment by aidanholm** [comment] 2017-12-02 10:37
@jeffmaner Actually, just had a thought: your issue might be caused by not having installed the dev packages for the dependencies. If you just installed the regular packages for sqlite, etc. then that won't work for compiling.

**Comment by jeffmaner** [comment] 2017-12-05 15:55
Brilliant, @aidanholm! That does seem to have been my problem. Once I downloaded all the dev packages for the dependencies, I was able to build. Almost. I got an error at what looks like the end.

```
...
luajit: build-utils/docgen/gen.lua:446: doc/apidocs/classes/widget:box.html: Invalid argument
stack traceback:
        [C]: in function 'assert'
        build-utils/docgen/gen.lua:446: in function 'write_file'
        build-utils/docgen/gen.lua:512: in function 'generate_documentation'
        ./build-utils/docgen/makedoc.lua:84: in main chunk
        [C]: at 0x004044a0
Makefile:84: recipe for target 'doc/apidocs/index.html' failed
make: *** [doc/apidocs/index.html] Error 1
```

I looked within `luakit/doc/apidocs/` and there is, indeed, no `index.html`.

**Comment by aidanholm** [comment] 2017-12-05 16:24
Great! I'll update the website docs, as it's not very clear at present.

I'm pretty sure the culprit is the `:` in the filename, which DOS doesn't like... I'll see what I can do to fix this.

In the meantime, if you're up for some makefile hacking, you can just disable docs generation. To do this, remove `apidoc` from line 20 (beginning with `all: `), and remove lines 100--103 (the lines under `install: all` mentioning `doc/apidocs/`.

**Comment by jeffmaner** [comment] 2017-12-05 16:45
After your suggested edits, `sudo make install`ing, and then restarting bash, success! :)

**Comment by aidanholm** [comment] 2017-12-05 17:03
:tada:

**Comment by ghost** [comment] 2017-12-05 18:50
I did not look into this earlier, sorry. Yes, linux on windows is a ubuntu, so the ubuntu (debian) install instruction apply aside from the special windows requirements (an up to date WSL that's no a deadly old ubuntu and an xserver like Xming, or Exceed for example).
