### ISSUE TITLE
Can't mark the checkbox

### ISSUE THREAD

**Issue by foras77** [luakit/luakit#629] opened 2017-12-12 04:22 UTC
Good day!

Can somebody help me with that trouble please.
I can not to mark the checkbox in that website:
www.spartex.kz
![screenshot - 12 12 2017 - 10 18 32](https://user-images.githubusercontent.com/34466808/33867300-f3195262-df25-11e7-8a6c-5c3252cb2f0a.png)
The checkbox marked by red arrow.

I click on this checkbox but nothing happens...
So i can't save my account into this website.
Of course, it is possible if i do it through any different web browser.
Somebody knows why it is unavailable?

Thanks.

**Comment by McSinyx** [comment] 2017-12-12 05:15
I can't reproduce the bug. Could you please provide futher infomation on you OS, webkit, luakit and lua version?

Here is the direct link in the screenshot to save others some time typing: https://www.spartex.kz/personal/order/?login=yes

**Comment by foras77** [comment] 2017-12-12 06:00
I can not to do it exactly by that link you stated.  OS Xubuntu 14.04:
Description:	Ubuntu 14.04.5 LTS
Codename:	trusty
luakit 2012.09.13-r1-8
Webkit 2.4.10-0ubuntu0.14.04.1
Lua... Afraid that installed two versions together:
5.1.5-5ubuntu0.1
and
5.2.3-1

**Comment by McSinyx** [comment] 2017-12-12 13:30
I'm afraid that the Luakit version you're using is too outdated. Try compiling the [current latest release](https://github.com/luakit/luakit/releases/tag/2017.08.10) or the `develop` branch and see if your problem is fixed. Please note that it's likely you'll need to compile WebKit2 to match at least version 2.16 as stated in the release I linked. (Currently the devs are working to [repackage the browser for Debian-based systems](https://github.com/luakit/luakit/projects), so sorry for the inconvenience.)

Also don't worry about having both Lua 5.1 and 5.2: Luakit know to choose to compatible version of the language.

**Comment by aidanholm** [comment] 2017-12-12 14:03
Normally you wouldn't have to compile webkit2gtk (which takes hours), just luakit (less than a minute); but you're running on an old version which probably won't have up-to-date packages for webkit2gtk. So you could also consider updating to 16.04 or later, which has packages for the latest webkit2gtk.

**Comment by n73red** [comment] 2017-12-14 02:27
Developer when the new version appears in the repositories debian sid?

**Comment by aidanholm** [comment] 2017-12-14 03:29
After the next release (v2.0.0)

**Comment by c0dev0id** [comment] 2020-09-07 07:47
Meanwhile we're at 2.2 and the author didn't come back. Also the page in question has changed, so I'm not able to retest. I'm closing the issue for now. Feel free to reopen it if the issue still occurs.

**Closed as completed by c0dev0id** 2020-09-07 07:47 UTC
Labels: outdated, question
