### ISSUE TITLE
Live on-the-fly command autocomplete

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#456] opened 2017-08-21 12:55 UTC
Hello there again. That would be really nice if there would be "real-time" autocompletition for commands and history as in qutebrowser(for example). That wouldn't be hard to implement. At the moment you already have autocompletition code. It's "fired" when user are pressing tab key. You just need to implement some listener that would "fire" autocompletition every time  input in luakit "command line" is changed. This would really improve usability, because clicking tab key is little bit annoying

**Comment by aidanholm** [comment] 2017-08-21 13:17
Hi! This is a duplicate of #297. I'll paste your comment there

**Closed as completed by aidanholm** 2017-08-21 13:17 UTC
