### ISSUE TITLE
All pages except the Luakit site not rendering

### ISSUE THREAD

**Issue by TimothyMischief** [luakit/luakit#693] opened 2018-03-28 07:16 UTC
I've just installed Luakit on my Arch VM and it's doing the strangest thing. It starts with the Luakit site running perfectly, I can browse around pages on the site without any problems. If I attempt to open a new page using the `o` prompt the new page won't render, instead I get a grey background. If I attempt to navigate away from the Luakit page via links (the github link for example) I see an empty white page but links and text fields within the site are interactable (the cursor changes to a text cursor/link finger and I'm able to follow links and enter text, I just can't see it.) If I navigate away from that tab though, the page becomes grey and I can no longer enter text/click links and the cursor remains the arrow cursor. If I try to open the luakit page from the `o` prompt it loads just fine.

I've found various results with different sites. But so far `luakit.github.io` is the only one that will render. `duckduckgo.com` loads a grey page, `start.duckduckgo.com` loads a white page that's interactable but invisible.

I have a feeling this may be thanks to running inside a Parallels VM. I've encountered a similar bug where qutebrowser will crash a tab so it only loads black occasionally and there's no way to fix it but close it and open a new tab. I'll try luakit on my dedicated arch laptop once I'm home, I imagine it will be fine.

I'm fully expecting this to be something I have to take to parallels and have them update their VM graphics drivers but thought I'd drop an issue here first to make sure I'm not missing anything obvious.

The machine with the problems:
Arch Linux LTS Kernel on a MBD 15" w. Touchbar via Parallels Desktop

EDIT: Worth mentioning that I can open dev tools and it works just fine, it reports no errors and shows rendering having successfully completed in the timeline.

**Comment by aidanholm** [comment] 2018-03-29 13:36
That's very odd. It does sound like it could be caused by running in Parallels. If it's not that, it's likely a Webkit bug. Luakit doesn't handle any web page rendering itself, but Webkit has had a few rendering glitches in the newest version, so that's also a possibility.

**Comment by c0dev0id** [comment] 2018-10-16 08:59
@TimothyDespair: Does this issue still occur? Did you find more information on it? Any luakit log entries (:log or console)?

Another idea would be to play with webkit freatures and disable graphics acceleration. Have you seen similiar effects on other webkit browsers (epiphany for example)?

**Comment by c0dev0id** [comment] 2018-10-21 18:48
@TimothyDespair: Another thing you could try is to `export LIBGL_DRI3_DISABLE=1` before starting luakit.

**Comment by c0dev0id** [comment] 2018-10-24 07:11
I accidently hit this issue. I was surfing around, opened a new tab, surfed around there, closed the new tab and the the "old" tab then was blank. I had the same "scroll" error in the log. Luakit was responsive, so I could copy (yy) the URL from the blank tab and /tabopen <paste> it and it opened in a new tab just fine. But the old tab stayed all white no matter what I did (also by opening other URLs).

Does this sound somewhat like the situation you experienced @TimothyDespair?
Unfortunately I didn't find a pattern to reproduce it. But I can confirm that this issue somehow exists.

**Comment by TimothyMischief** [comment] 2018-11-15 13:19
Sorry, I've been inactive for a while. That sounds a lot like what was happening! It's been a while since I've fired up the Arch VM, I'll try to give it a shot in the next couple of days and I'll let you know how it goes. (You may also have inadvertently given me a fix for an issue I'm having with Luakit on the raspberry pi I just bought with the LIB_GL_DRI3 fix too.) I've also more or less migrated to Alpine linux, (which doesn't do great in a VM) but I've got a Void and an Alpine VM in parallels I'll try luakit across a few of them, see whether I can nail down a pattern.

**Comment by TimothyMischief** [comment] 2018-11-18 01:29
It looks like I'm no longer able to replicate this issue. Everything seems to be working perfectly as of now on the arch virtual machine. I also tried it out in a void vm and it seems to be working fine there too. This is all under parallels desktop, I've also tested under VirtualBox and it's fine there too (but I've never seen the problem there.)

The arch VM has been sitting untended for about 3 months, so there was a fair backlog of updates to luakit and the rest of the system, it's hard to know where the change happened. I tried to test before upgrading, but it seems like I'd removed luakit at some point so I could only test with the latest build.

Whatever was happening it seems to have resolved for me.

**Comment by McSinyx** [comment] 2018-11-18 14:55
So maybe we can close this issue for now?

**Comment by TimothyMischief** [comment] 2018-11-19 01:26
Unless @c0dev0id has managed to find anything more on his end. Even then, might be best to close this one and open a new one, for clarity's sake.

**Comment by c0dev0id** [comment] 2018-11-19 08:50
Let's close it for now.

**Closed as completed by c0dev0id** 2018-11-19 08:50 UTC
