### ISSUE TITLE
Error while open bookmarks/history page

### ISSUE THREAD

**Issue by fiziologus** [luakit/luakit#625] opened 2017-12-08 18:20 UTC
```
[   35.525732] E [lua/chrome]: /usr/local/share/luakit/lib/bookmarks_chrome.lua:503: attempt to index local 'opts' (a nil value)
                 Traceback:
                 (1) /usr/local/share/luakit/lib/bookmarks_chrome.lua:503 in function [anonymous]
                 (2) [C]                                                  in function xpcall
                 (3) /usr/local/share/luakit/lib/chrome.lua:310           in function [anonymous]

[ 1090.471108] E [lua/chrome]: /usr/local/share/luakit/lib/history_chrome.lua:334: attempt to index local 'opts' (a nil value)
                 Traceback:
                 (1) /usr/local/share/luakit/lib/history_chrome.lua:334 in function [anonymous]
                 (2) [C]                                                in function xpcall
                 (3) /usr/local/share/luakit/lib/chrome.lua:310         in function [anonymous]
```
With empty bookmarks/history list.

_Note: Edited by A.H: add code formatting_

**Comment by aidanholm** [comment] 2017-12-09 09:31
Thanks for reporting! I'm guessing that you are on version 2017.08.10

This is a duplicate of #466, and is already fixed in `develop`. To get things working, you could either install a 2017.08.10 package that uses LuaJIT (if one is available), or build from the latest develop with either regular lua or LuaJIT.

**Comment by fiziologus** [comment] 2017-12-09 19:05
> Thanks for reporting! I'm guessing that you are on version 2017.08.10

Yes. I not like unstable (bugs, nerves and other stuff).
>To get things working...

I change more easy way: just apply https://github.com/luakit/luakit/commit/c9b4f92abc273022637fcb4790ff6f7fd35cd36d. Now all work. Thanks for help. Closed.

**Comment by hippi777** [comment] 2017-12-09 21:11
hi there! :)

is that a data loss or just an app fail? im deeply afraid of data loss, cuz im doing always much researches with a s#itload of tabs opened like now i have more than 600 :D my best guess to make sure not getting into this kinda trouble is to save the db before and after run the app via a supervisoir, however id like to ask how much possibility exists around lk to get this unwanted point, but thats kinda like asking for predict future :D

btw what about 'lk' shorthand for speed up human workflow all around? :) in scripting, in commands and 'lk://'

**Comment by aidanholm** [comment] 2017-12-10 11:13
App failure: the bookmarks + history pages need to call Lua from the JS running on the page, which is where the bug was. So it's only a display bug, not a corruption issue.

Data loss... luakit saves a recovery session periodically: if you absolutely need to make sure you can recover your work, I'd use an inotify hook to copy each version of the recovery session file somewhere safe. Even if the file itself is corrupted for some reason and can't be read, it's still possible to pull the URLs out: the format is text-based and very simple.

`lk://` might be nice actually; that's a good idea. Separately, I was considering moving _all_ built-in modules to a single `lk` namespace, a la mpv's `mp` namespace.

**Comment by hippi777** [comment] 2017-12-10 23:19
thx! ill keep this msg for myself, so when ill reach the point of migration, then ill go deeper and come back in case of need :)

**Closed as completed** 2017-12-11 09:20 UTC
