### ISSUE TITLE
open link in new tab displays only blank page

### ISSUE THREAD

**Issue by twnaing** [luakit/luakit#834] opened 2020-04-15 19:58 UTC
## Current Behavior

- only shows blank page on choosing "Open Link in New Tab" right click menu

## Expected Behavior

- should show web page (of the right-clicked link)

## Reproduction Instructions

- right click link
- choose open link in new tab
- observe LuaKit open new tab showing blank page

## Environment

Linux Distribution & Version: Arch Linux
Output of `luakit --version`: luakit 2.1-33-g0de4b1c0 built with webkit 2.28.1 (installed version: 2.28.1)

**Comment by CodeJoule** [comment] 2020-04-16 17:25
Take a look at #804 and #815.

Edit: It doesn't work for me either; I didn't realize #815 was already merged into the develop branch. I had thought it was still waiting to be merged. In the meantime, you can press `r` to make the page load.

**Comment by CodeJoule** [comment] 2020-04-16 17:42
By the way, you can press `r` to make the page load.

**Comment by craftyguy** [comment] 2020-04-18 03:02
This seems to be caused by my patch here https://github.com/luakit/luakit/commit/e3338495323b8d696c2bc53e4e6d0011bb4d0e99, in merge request #830.

I thought `arg` being nil meant `:open` or `:tabopen` was called without an uri, but apparently links that open a new tab also end up in `new_tab` without `arg` being set. I'm pretty new to the luakit codebase, and currently have no idea how that even worked before when no uri/arg was passed in.

**Comment by twnaing** [comment] 2020-04-18 09:20
So, this is a __know issue__. 

The current workaround is __reload__ (press `r`) after seeing the blank page.

**Comment by MarcoBeishuizen** [comment] 2020-04-23 15:14
Here the reload workaround only works on the 2.1 release version. It doesn't on the 2.1.33 dev version. I'm running Luakit on FreeBSD 12.1-RELEASE.

**Comment by craftyguy** [comment] 2020-04-23 20:35
Right, the workaround mentioned above is for the release version, and is a workaround for an issue already fixed in the development branch..

The workaround does not work for the issue caused by e3338495323b8d696c2bc53e4e6d0011bb4d0e99. This patch could be reverted, or someone could help me understand how I could determine if a new tab is a 'new blank tab' or a 'new tab that loads a url', since I can't find a way to distinguish between the two in the `new_tab` function..

**Comment by zappathustra** [comment] 2020-07-02 14:48
#854 is probably related.

**Closed as completed** 2020-07-05 12:55 UTC

**Comment by aidanholm** [comment] 2020-07-05 12:56
Should be fixed now; sorry for the delay, and thanks for the pointer to e333849!
