### ISSUE TITLE
Continuous CPU usage when idle

### ISSUE THREAD

**Issue by zsugabubus** [luakit/luakit#797] opened 2019-07-28 21:29 UTC
## I'm submitting a…
Bug Report

## Current Behavior
At least 1-2%, continuous CPU usage when idle (only one, blank tab is opened). I measure it in "WebKitWebProcess"(es), but other WebKit-based browsers don't seem affected.

## Expected Behavior
No CPU usage at all.

## Reproduction Instructions
Just open one or more blank tabs.

## Environment
Linux Distribution & Version: Arch
Output of `luakit --version`: luakit 2.1 built with webkit 2.24.3 (installed version: 2.24.3)
Configuration files: None

**Comment by craftyguy** [comment] 2019-12-05 01:55
I can still reproduce this on webkit 2.26, and I built/tested webkit 2.27 where this still happens. I see much higher CPU usage in luakit/WebKitWebProcess, basically what amounts to 100% cpu usage on 1 core when displaying even the simplest html page:

```
<html>
RIP battery life
</html>
```

Definitely do not see this problem with Midori and other webkit2 browsers, and originally reported.

**Comment by esbjerg** [comment] 2020-01-09 12:00
Also seen on my FreeBSD based computers. luakit-2.1,1, webkit2-gtk3-2.26.2 from ports on both FreeBSD 11.3 and 12.1. Seen on laptops with Intel graphics and workstations with Nvidia and AMD graphics. Same behavior.

I used the same simple html as suggested above.

CPU usage stays on 12-15% for the webkit process, 6-12% for the luakit process and 4-7% for the Xorg process. CPU's are Core i7 and Xeon's.
It is very noticeable since battery life is affected.

I ran the inspector and it looks like the webpage is re-rendered every other second.
I ran midori using the same html page there is only CPU usage upon load of the page. 
I ran the inspector while using midori and noticed that there is 0 Java Script rendering usage in midori as opposed to luakit. Since the page does not contain javascript something is off. Also the layout subproces uses way less CPU in midori.

**Comment by craftyguy** [comment] 2020-01-09 18:34
@esbjerg I believe it is related to this: https://github.com/luakit/luakit/issues/804

Reverting the commit I mentioned in that comment has resolved the high CPU usage for me at least, but if it doesn't for you then perhaps there is some other issue..

**Comment by CodeJoule** [comment] 2020-04-15 01:03
I have this issue too; I am getting 80%-95% CPU usage on all 4 cores, on my Thinkpad T420. I will mention that my laptop does have Intel graphics, since @esbjerg mentioned it may be relevant.

Edit: Whoops, this is when I have a several (~7) pages up. When idle, solely on the default webpage (LuaKit's home), it still has around %15 CPU usage (according to `htop`).

Is the 80%-95% issue related to this, or do I need to make a new thread for that?

Okay last edit: When the only page is youtube.com, LuaKit is using ~80% CPU as well, no other tabs. :frowning_face:

**Comment by CodeJoule** [comment] 2020-04-15 04:22
Okay, so I may have spoken too soon. I cloned the develop branch and it's all fixed. Idle, CPU usage goes down to 0%-1%, which also happens on YouTube after the page is loaded and no activity is happening. Wow! I am going to figure out how to get the develop branch installed on my system instead of the version that is packaged.

Edit: I'm using FreeBSD FWIW. I apologize, I should have tested out this repository first instead of the pre-packaged version.
Another Edit: Actually, I think the LuaKit's CPU usage when idle is %0, I actually meant my whole system's CPU usage is %0-%1, which means everything is normal. Probably means LuaKit is not working with the CPU at all when idle. So it should be fixed.

**Comment by CodeJoule** [comment] 2020-04-15 07:06
Oof, nevermind. It does the crazy CPU thing on github.com. :frowning: (Using the repository build)
Edit: Okay IDK what changed, now GitHub is completely fine... :/

Edit 2: Whoops, for some reason my WM was launching the old version (even though I input the correct path), when I make sure I launch it with a terminal emulator and a shell (with the same path), everything seems completely fine. I'll look around more.

**Comment by aidanholm** [comment] 2020-07-05 13:30
Tentatively closing; I'm seeing idle CPU of 0% on both luakit and webkit processes, and the offending commit has been reverted. Feel free to reopen again if this pops up again, and thanks for the information everyone!

**Closed as completed by aidanholm** 2020-07-05 13:30 UTC
Labels: bug
