### ISSUE TITLE
Luakit 2017.08.10 following links not working sometimes

### ISSUE THREAD

**Issue by curioussavage** [luakit/luakit#567] opened 2017-10-21 04:25 UTC
I tried reddit and hacker news. On reddit It displayed the numbers by links but nothing happened after selecting one. On hacker news they didn't show up at all.

![luakiterrors](https://user-images.githubusercontent.com/7064600/31847999-aa707cec-b5dc-11e7-904d-984fdf0f92a8.png)

**Comment by aidanholm** [comment] 2017-10-21 07:39
I can't reproduce this. The logs indicate that the follow-mode state is becoming desynced with the select module state, for some reason. Do you remember what you were doing before encountering this issue?

**Comment by curioussavage** [comment] 2017-10-21 18:44
I tried It a few times and restarted the browser in between. I’m pretty sure this time I just started the browser navigated to Reddit and hit f and tried to select a link to follow.

If I can later today I will add some more logging in those functions.

**Comment by aidanholm** [comment] 2017-10-22 11:26
Do you have any changes to your rc file?

**Comment by curioussavage** [comment] 2017-10-23 20:31
No changes to my rc file.

Should add this is on a chromebook on an Ubuntu 16 based distro. I built from source. Don't see this issue at all on my desktop but I think I installed using apt there.

I tried adding a bunch of message arguments to the lua `assert` calls but It doesn't look like the application surfaces those messages.

**Comment by aidanholm** [comment] 2017-10-23 20:38
`assert` doesn't take a format string; you could add the following to rc.lua though:
```lua
local orig_assert = assert
assert = function (c, f, ...) return orig_assert(c, type(f) == "string" and f:format(...) or c) end)
```
This might also break horribly; didn't test it

**Comment by aidanholm** [comment] 2017-10-23 21:07
I would suggest logging the output of `debug.traceback()` at the entry points of the `enter`, `leave`, and `focused_hint` functions in `select_wm`, and examin the order in which they occur when you enter follow mode and follow the first link.

**Comment by curioussavage** [comment] 2017-10-24 04:33
How do I log? I tried to use the global `msg` table (info, verbose) but nothing gets logged in the app. You don't have to rebuild the app when the lua code changes right? I'm pretty sure the answer to that is no but I tried that just in case. Ran the app with the verbose flag.

**Comment by curioussavage** [comment] 2017-10-24 04:34
regardless the issue I see now is the `overlay` element is not there. Or at least the reference to it in lua is not ( I haven't opened the web inspector to try to check for it when that happens)

**Comment by curioussavage** [comment] 2017-10-24 05:07
oh boy. I didn't notice where it installed the libraries. so I was building and running the binary in the repo. Didn't realize the lua libs it was using were from the global install

**Comment by aidanholm** [comment] 2017-11-03 12:40
Any luck tracking this issue down?

**Comment by curioussavage** [comment] 2017-11-03 19:57
I can't replicate it any more on my Chromebook after running `make install` again. So it seems something was left in a bad state in a previous install :man_shrugging:

**Comment by aidanholm** [comment] 2017-11-05 21:45
I'm glad to hear it's working again :) I guess I'll close this issue then, but feel free to reopen it if the issue reoccurs

**Closed as completed by aidanholm** 2017-11-05 21:45 UTC
