### ISSUE TITLE
Open URL in Place?

### ISSUE THREAD

**Issue by jnunez166** [luakit/luakit#289] opened 2015-08-04 03:33 UTC
From rc.lua I can set if new page request open in a new tab or a new window. How can I make them open in the current window?

I am using luakit and raspberry pi to display a status page. I also publish a page where my family can switch the page between various status pages. Currently every request is opening the url in a tab. I would like to open them in the current window instead.

**Comment by o-jasper** [comment] 2015-08-04 17:20
Not sure what you mean, left-click by default is current window. If you look at `:help`, the `:open` command shows that `window:navigate(to_url)` should work?

Otherwise, you can also see that in all-mode, maybe redefining `<mouse1>` might allow you to make it navigate instead.

**Comment by jnunez166** [comment] 2015-08-04 20:59
I'm sorry I didn't specify that there is no mouse or keyboard attached. I publish a few web pages on a raspberry pi that when you select an option the apache web server will execute "luakit http://...". The display connected to the Raspberry Pi displays the new page (thanks to LuaKit)

rc.lua checks for unique and if not it triggers a "tab open" or "window new" call. It's at this stage that I would like to open the url within the same window.

**Comment by o-jasper** [comment] 2015-08-05 20:48
Right, instead of having something like a javascript timer that pokes the server constantly?

Could iterate `window.tabs` for the views that are relevant. (actually, dont see it; `:lua window.tabs` seems nil..)

Alternatively could add something to `view:add_signal("resource-request-starting", function (v, uri) .. ` to remember which tabs are from that server, and then if libunique gets input, you recognize it again, and instead poke the appropriate views to reload.

**Comment by aidanholm** [comment] 2017-06-15 03:59
If you want `luakit example.com` to always open example.com in the current tab, then you only need to change `config/rc.lua`; change `ww:new_tab(arg)` to ` ww:navigate(arg)`.

**Comment by c0dev0id** [comment] 2018-10-21 21:07
The issue is 3 years old and the solution has been implemented. I'm closing this now.

**Closed by c0dev0id** 2018-10-21 21:07 UTC
Labels: question
