### ISSUE TITLE
Can't set/load settings or settings_chrome in userconf.lua

### ISSUE THREAD

**Issue by 4217th** [luakit/luakit#719] opened 2018-09-11 00:56 UTC
In my userconf.lua I load the mode module to change keybinds and the vertical_tabs module and they work as expected.

```
local settings = require "settings"
local settings_chrome = require "settings_chrome"
```
Either of those lines however cause the entire userconf.lua to no longer work. I'm really just trying to set my homepage (settings.window.home_page = "xyz")

luakit --check returns syntax  OK

**Comment by aidanholm** [comment] 2018-09-11 12:10
Those lines both work fine for me; there might be an error elsewhere that's being triggered by these lines.

Is there any error message? If not, what is the nature of the failure?

**Comment by 4217th** [comment] 2018-09-11 12:45
There are no error messages, luakit simply starts as if userconf.lua was empty. Commenting the lines out the other settings are applied again. I made no changes/additions other than
```
mkdir -p ~/.config/luakit/
cp /etc/xdg/luakit/rc.lua ~/.config/luakit/ 
```
and

`require "userconf"  `

in the  ~/.config/luakit/rc.lua

userconf.lua itself I can limit it to just 
```

local settings = require "settings"
local settings_chrome = require "settings_chrome"
local vertical_tabs = require "vertical_tabs"
```

to reproduce the erroneous behaviour, order of the lines makes no difference either.

OS is manjaro i3 community edition

**Comment by aidanholm** [comment] 2018-09-11 15:32
That seems unusual; is there anything shown in `luakit://log`?

`luakit --check` won't (can't) check `userconf.lua`; it's possible you have a syntax error in there, although I'm not sure where it would come from, since those lines look fine, and work fine on my computer. You could use `luakit --check --config path/to/userconf.lua` to check that.

**Comment by c0dev0id** [comment] 2018-10-24 07:03
@4217th: Do you still have this issue? Sometimes the sequence of statements in rc.lua make a difference. If you can share your `rc.lua` and `userconf.lua` as a whole, we can properly reproduce/retest your case.

**Comment by c0dev0id** [comment] 2020-09-17 21:25
No author reaction -> closing.

**Closed as completed by c0dev0id** 2020-09-17 21:25 UTC
