### ISSUE TITLE
Feature request: Notification for downloads page

### ISSUE THREAD

**Issue by vitamins** [luakit/luakit#205] opened 2013-04-30 18:22 UTC
Currently when a download is running in luakit you have to open the downloads tab and check if it is finished from time to time. Adding a notification when a download is finished would be nice to have. I suggest changing the title of the downlads tab to indicate this or changing the tab's color. Also the X11 alarm should be set, so the window is marked as "requires attention" in the window manager.
(This is the alarm you get from echo -e '\a' .)
Last but not least it would be nice to have a seperate downloads window, even if you set new pages to be opened as tabs.

**Comment by aidanholm** [comment] 2017-07-02 18:48
You can listen to the `download::status` signal on the `downloads` module to react when a download is complete. Something like this:
```
local downloads = require "downloads"
downloads.add_signal("download::status", function (d, data)
    if d.status == "finished" then
        luakit.windows[1].urgency_hint = true
    end
end)

**Comment by c0dev0id** [comment] 2020-09-05 20:15
As a solution has been provided and the issue is quite old, I'm closing it. Feel free to reopen it in case of more questions.

**Closed by c0dev0id** 2020-09-05 20:15 UTC
Labels: feature-request
