### ISSUE TITLE
Password fields are hinted based on their hidden/masked content

### ISSUE THREAD

**Issue by matteopt** [luakit/luakit#1030] opened 2023-01-01 12:49 UTC
**Current Behavior:**
When pressing `f` to enter follow mode, password fields are hinted based on their (hidden/masked) content.

**Desired Behavior:**
Never hint password fields based on their hidden/masked content.

**How can we reproduce it (step by step):**
1. Open any login page (e.g. Google)
2. Enter something in the password field (it may help to enter something that's already on the page, e.g. "Forgot")
3. Enter follow mode and search for what's been entered in the password field
4. The password field will be hinted or followed/focused

**Hint to fix this:**
Around [L286](https://github.com/luakit/luakit/blob/develop/lib/select_wm.lua#L286) of select_wm.lua  
I'm not sure what properties `element` has but it should be simple to check if input type equals password

**Environment:**

Linux Distribution & Version: Arch Linux
Output of `luakit --version`:
```
luakit 2.3.3
  built with webkit 2.38.2 (installed version: 2.38.3)
```

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment] 2023-01-02 02:56
Thanks for noticing.
I can't reproduce this, but i believe you.
Would you try this patch:
```
diff --git a/lib/select_wm.lua b/lib/select_wm.lua
index 94dc53ee..3af01420 100644
--- a/lib/select_wm.lua
+++ b/lib/select_wm.lua
@@ -283,9 +283,12 @@ local function frame_find_hints(page, frame, elements)
         local rbb = get_element_bb_if_visible(element,wbb, page)
 
         if rbb then
-            local text = element.text_content
-            if text == "" then text = element.value or "" end
-            if text == "" then text = element.attr.placeholder or "" end
+            local text = ""
+            if element.type ~= "password" then
+                local text = element.text_content
+                if text == "" then text = element.value or "" end
+                if text == "" then text = element.attr.placeholder or "" end
+            end
             hints[#hints+1] = { elem = element, bb = rbb, text = text }
         end
     end
```

In this context `element` is a `dom_element`, and it's properties are documented in the API available [online](http://luakit.github.io/docs/classes/dom_element.html), and as a luakit chrome page: luakit://help/doc/classes/dom_element.html.


You could also avoid the behaviour you're describing by only matching against the label text:
```lua
local follow = require "follow
follow.pattern_maker = follow.pattern_styles.match_label
```
...but having a potential data leak in the default behaviour is sub-optimal.

**Comment by matteopt** [comment] 2023-01-02 12:28
Thanks for the reply.  
I'm not sure why you're not able to reproduce this behaviour, perhaps you have different settings? I tested this on a clean build from the develop branch.  
  
Thank you for the info about `dom_element`, that helps a lot.  
I would still find it useful to match text content as long as the field is not masked.  
  
Thank you also for providing the patch, I found that nothing could be hinted by text after applying it, I believe it was just a little mistake with variable assignment, the following patch works well for me at the moment:  

```
diff --git a/lib/select_wm.lua b/lib/select_wm.lua
index 94dc53ee..3af01420 100644
--- a/lib/select_wm.lua
+++ b/lib/select_wm.lua
@@ -283,9 +283,12 @@ local function frame_find_hints(page, frame, elements)
         local rbb = get_element_bb_if_visible(element,wbb, page)

         if rbb then
-            local text = element.text_content
-            if text == "" then text = element.value or "" end
-            if text == "" then text = element.attr.placeholder or "" end
+            local text = ""
+            if element.type ~= "password" then
+                text = element.text_content
+                if text == "" then text = element.value or "" end
+                if text == "" then text = element.attr.placeholder or "" end
+            end
             hints[#hints+1] = { elem = element, bb = rbb, text = text }
         end
     end
```
  
However, I think matching the placeholder is still sound, even for password fields, hence I think this patch is slightly better:  

```
diff --git a/lib/select_wm.lua b/lib/select_wm.lua
index 94dc53ee..ee2b1491 100644
--- a/lib/select_wm.lua
+++ b/lib/select_wm.lua
@@ -283,8 +283,11 @@ local function frame_find_hints(page, frame, elements)
         local rbb = get_element_bb_if_visible(element,wbb, page)

         if rbb then
-            local text = element.text_content
-            if text == "" then text = element.value or "" end
+            local text = ""
+            if element.type ~= "password" then
+                text = element.text_content
+                if text == "" then text = element.value or "" end
+            end
             if text == "" then text = element.attr.placeholder or "" end
             hints[#hints+1] = { elem = element, bb = rbb, text = text }
         end
```
  
It looks like this `frame_find_hints` function is not used by anything else, I think it would be ok to modify it directly. I'm not sure if anything else needs to be checked or confirmed. If you wish, I can open a pull request with the changes.

**Comment by taobert** [comment] 2023-01-02 23:34
> I'm not sure why you're not able to reproduce this behaviour, perhaps you have different settings?

IDK. Neither setting `follow.pattern_maker` back to default, nor removing my `~/.config/luakit` directory allowed me to match anything other than the hint labels, so i've changed something somewhere, but i'm spinning a few other plates at the moment and didn't want to go down a rabbit hole of "Why does something that _should_ work _not_ work?".

Please _do_ open a PR, but i'm not the one who'll ok it, so you might have to wait a bit.

**Comment by c0dev0id** [comment] 2024-01-23 22:58
I was able to reproduce the issue and merged the PR. Thanks!

**Closed as completed by c0dev0id** 2024-01-23 22:58 UTC

**Comment by matteopt** [comment] 2024-01-24 17:04
Thank you!
