### ISSUE TITLE
Is there a way to use DjView NPAPI plugin with Luakit Web Browser?

### ISSUE THREAD

**Issue by jsbien** [luakit/luakit#852] opened 2020-06-08 15:05 UTC
Cf. e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962181

**Comment by bodqhrohro** [comment] 2020-08-04 14:37
Are other plugins working for you? The support for GTK+2 NPAPI plugins was surely removed in WebKitGTK+ 2.26, and they could possibly break others as well.

**Comment by jsbien** [comment] 2020-08-04 15:18
I'm no longer interested in Luakit Web Browser, as there is usable, although not perfect, DjVu extension for Firefox (https://djvu.js.org/)

**Comment by c0dev0id** [comment] 2020-09-05 14:43
As the issue is already answered (NPAPI support got removed) and the Author is not interested in luakit anymore, I'm closing this issue.

**Closed as completed by c0dev0id** 2020-09-05 14:43 UTC
